#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="Bash TUI"
TITLE="Welcome!"
MENU="Select a Login Server"
export PORT=1

OPTIONS=(1 "KDE")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose GDM2"
            /usr/local/bin/vncserver-gdm2
            ;;
        2)
            echo "You chose Lightdm"
            /usr/local/bin/vncserver-lightdm
            ;;
esac
