#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="X.Org Server"
TITLE="Vncserver Starter"
MENU="Select WM and DE"
export PORT=1

OPTIONS=(1 "Start vncserver with Gnome"
         2 "Start vncserver with I3wm")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose Gnome"
            export USER=root
            export HOME=/root
            vncserver -name Volna -localhost no :1 -xstartup ~/.vnc/xstartup-gnome
            ;;
        2)
            echo "You chose I3wm"
            export USER=root
            export HOME=/root
            vncserver -name Volna -localhost no :1 -xstartup ~/.vnc/xstartup-i3wm
            ;;
esac
