#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="XFree 86"
TITLE="Vncserver Starter"
MENU="Select WM and DE"
export PORT=1

OPTIONS=(1 "Start vncserver with Gnome"
         2 "Start vncserver with Openbox")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose Gnome"
            export USER=root
            export HOME=/root
            vncserver -name Volna -localhost no :1 -xstartup ~/.vnc/xstartup-gnome
            ;;
        2)
            echo "You chose Openbox"
            export USER=root
            export HOME=/root
            vncserver -name Volna -localhost no :1 -xstartup ~/.vnc/xstartup-openbox
            ;;
esac
