#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="Gdm2"
TITLE="Welcome!"
MENU="Select a Session"
export PORT=1

OPTIONS=(1 "Gnome 2"
         2 "I3wm")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose Gnome"
            export USER=root
            export HOME=/root
            vncserver -name Volna -localhost no :1 -xstartup ~/.vnc/xstartup-gnome
            ;;
        2)
            echo "You chose I3wm"
            export USER=root
            export HOME=/root
            vncserver -name Volna -localhost no :1 -xstartup ~/.vnc/xstartup-i3wm
            ;;
esac
