#!/bin/bash

export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=5
BACKTITLE="Lightdm"
TITLE="Welcome!"
MENU="Select a Session"
export PORT=1

OPTIONS=(1 "XFCE")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose XFCE"
            export USER=root
            export HOME=/root
            vncserver -name Volna-X -localhost no :1 -xstartup ~/.vnc/xstartup-xfce
            ;;
esac
